Burger-menu
js-tasks-ru/htmlcss-20230227_mike-nk-nk pull request #17
Opened 2023-03-28 14:23 UTC by MikeMikle3

2023-03-29 09:23 UTC, GSemikozov requested changes

2023-03-29 09:23 UTC, GSemikozov commented on 09-lection7/01-burger-menu/burger-menu.css
> +.burger-menu__header-rect{
если такое лого переиспользуем / дублируем код из хедера - тогда лучше создать отдельный компонент

2023-03-29 09:23 UTC, GSemikozov commented on 09-lection7/01-burger-menu/burger-menu.css
> +.burger-menu__item_separator{
не модификатор а элемент - .burger-menu__item-separator

2023-03-29 09:23 UTC, GSemikozov commented on 09-lection7/01-burger-menu/burger-menu.css
> +.burger-menu__item_title{
элемент .burger-menu__item-title

2023-03-29 09:23 UTC, GSemikozov commented on 09-lection7/01-burger-menu/index.html
> +                    <div class="burger-menu__header-close" id="burger-menu-close">
button

2023-03-29 09:23 UTC, GSemikozov commented on 09-lection7/01-burger-menu/index.html
> +                    <div class="burger-menu__header-rect"></div>
logo

2023-03-29 09:23 UTC, GSemikozov commented on 09-lection7/01-burger-menu/index.html
> +                    <div class="burger-menu__item burger-menu__item_separator"></div>
burger-menu__item-separator

2023-03-29 09:23 UTC, GSemikozov commented on 09-lection7/01-burger-menu/index.html
> +                    <div class="burger-menu__item burger-menu__item_checkbox">
переключалку темы еще не верстали, удалим

2023-03-29 09:23 UTC, GSemikozov commented on 09-lection7/01-burger-menu/index.html
> +                    <div class="burger-menu__item burger-menu__item_title">Components</div>
h5, просто burger-menu__item-title

2023-03-29 18:35 UTC, MikeMikle3 commented on 09-lection7/01-burger-menu/burger-menu.css
> +.burger-menu__item_separator{
там ВСЕ пункты меню .burger-menu__item
с фонтом, цветом...
а это модификаторы конкретных типов
Но ок, переделаю

2023-03-29 18:36 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-03-29 19:25 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-03-30 10:49 UTC, GSemikozov commented on 09-lection7/01-burger-menu/burger-menu.css
> +.burger-menu__item_separator{
разделитель - это просто полоса, в ней нет никакого текста))

2023-03-30 10:50 UTC, merged