Кнопки и аккордеон
js-tasks-ru/htmlcss-20230227_mike-nk-nk pull request #4
Opened 2023-03-10 17:32 UTC by MikeMikle3

2023-03-10 17:33 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-03-15 00:29 UTC, GSemikozov requested changes

2023-03-15 00:29 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    font-style: normal;
не хватает font-family

2023-03-15 00:29 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    min-height: 48px;
просто height

2023-03-15 00:29 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    font-style: normal;
не хватает паддингов

2023-03-15 00:29 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    cursor: pointer;
можно указать сразу на .button

2023-03-15 00:29 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    cursor:not-allowed;
лучше pointer-events: none

2023-03-15 00:29 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    max-width: 730px;
лишнее ограничение

2023-03-15 00:29 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    /*color:red;*/
тут наверно паддинг снизу будет другой (32)

2023-03-15 00:29 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    color: var(--black);
+ list-style: none

2023-03-15 00:29 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    color: var(--black);
и наверно еще нужен отступ сверху

2023-03-17 09:22 UTC, MikeMikle3 commented on 03-lection1/02-accordion/accordion.css
> +    color: var(--black);
если без \<p>\</p> то  для отступа добавил 

.accordion__item[open] .accordion__summary{
    padding-bottom: 16px;
}

2023-03-17 09:22 UTC, MikeMikle3 commented on 03-lection1/02-accordion/accordion.css
> +    /*color:red;*/
тогда вроде \<p>\</p> не нужно

2023-03-20 12:51 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    color: var(--black);
нет, отступ нужен у всего accordion__item - 32 снизу, и текст должен быть звернут в какой-то элемент, причем лучше div )

2023-03-22 12:04 UTC, GSemikozov requested changes

2023-03-22 12:04 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    color: var(--black);
все еще актуально - весь скрытый контент надо завернуть в div с классом например .accordion__content

2023-03-25 13:56 UTC, GSemikozov approved these changes

2023-03-25 13:56 UTC, merged