Cards chart skeleton
js-tasks-ru/htmlcss-20230227_mike-nk-nk pull request #5
Opened 2023-03-13 07:03 UTC by MikeMikle3

2023-03-13 07:03 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-03-15 00:34 UTC, GSemikozov requested changes

2023-03-15 00:34 UTC, GSemikozov commented on 04-lection2/01-histogram/chart.css
> +.chart{
не стоит элементы гистограммы оформлять как отдельные блоки)
это касается всех элементов ниже.

2023-03-15 00:34 UTC, GSemikozov commented on 04-lection2/01-histogram/chart.css
> +.chart{
для данного элемента договаривались ставить фикс высоту 50px, чтобы дочерним элементам задавать высоту в процентах

2023-03-15 00:34 UTC, GSemikozov commented on 04-lection2/01-histogram/chart.css
> +    display: block;
лишнее

2023-03-15 00:34 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    justify-content: space-between;
лишнее

2023-03-15 00:34 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    padding: 16px 24px 0px 24px;
чтобы не задавать на каждом дочернем элементе однотипные паддинги - лучше задать их сразу на уровне блока

2023-03-15 00:34 UTC, GSemikozov commented on 04-lection2/01-histogram/index.html
> +                <div class="histogram-header__item-right">
это histogram__link, tag `<a>`

2023-03-15 00:34 UTC, GSemikozov commented on 04-lection2/01-histogram/index.html
> +       <histogram class="histogram" style="width:354px; height:185px; margin:16px;">
высоту даже здесь не стоит фиксировать

2023-03-15 00:34 UTC, GSemikozov commented on 04-lection2/02-skeleton/index.html
> +        <div class="skeleton" style="width: 579px; height: 192px; margin:16px">
высоту и ширину удалим

2023-03-15 00:34 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__elem1{
названия элементов по типу elem1 очень не информативны, лучше продумать более смысловое название

2023-03-15 00:34 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    padding-bottom: 16px;
если отталкивается от внешних элементов - то margin

2023-03-15 00:34 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__elem2{
см выше

2023-03-15 00:34 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    width: 172px;
ширину в процентах (приблизительно)

2023-03-15 00:34 UTC, GSemikozov commented on components/content/content.css
> +    padding: 68px 165px 68px 165px;
вместо таких паддингов (165px) нужно использовать container

2023-03-15 00:34 UTC, GSemikozov commented on index.html
>              <div class="header">Header</div>
`<header>`

2023-03-15 00:34 UTC, GSemikozov commented on index.html
>              <div class="footer">Footer</div>
`<footer>`

2023-03-17 09:36 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-03-17 12:45 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-03-20 12:53 UTC, GSemikozov requested changes

2023-03-20 12:53 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    text-align: right;
лишнее

2023-03-20 12:53 UTC, GSemikozov commented on 04-lection2/01-histogram/index.html
> +                    <div>Total orders</div>
здесь тоже должен быть соответствующий класс

2023-03-20 12:53 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__line_l3{
.skeleton__line_large

2023-03-20 12:53 UTC, GSemikozov commented on components/content/content.css
> +    padding: 68px;
точно ли нужно со всех сторон?

2023-03-20 14:53 UTC, merged